"""amani

Revision ID: 946cb1101b45
Revises: 
Create Date: 2024-02-11 18:04:05.672489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '946cb1101b45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'trigger_event', ['trigger_event_id'], ['id'])

    with op.batch_alter_table('trigger_event', schema=None) as batch_op:
        batch_op.drop_constraint('trigger_event_ibfk_1', type_='foreignkey')
        batch_op.drop_column('risk_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trigger_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('trigger_event_ibfk_1', 'risk', ['risk_id'], ['id'])

    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trigger_event_id')

    # ### end Alembic commands ###
